<template>
    <footer>
        <h4>Disclaimer: No user data is stored. Recommendations may be inaccurate as they are generated by an AI model.
            Media
            search functionality is powered by TMDB, whose free database enables this application.
        </h4>
    </footer>
</template>
<style lang="less" scoped>
@import "@/variables.less";

footer {
    color: rgba(189, 189, 189, 0.842);
    width: 100%;
    background-color: fade(black, 30%);
    backdrop-filter: blur(5px);

    h4 {
        padding: @spacing-md;
    }
}
</style>